[package]
name = "klip"
description = "Copy/paste anything over the network"
version = "0.3.0"  #:version
authors = ["Isis Ebsen <isis@5ht2.me>"]
license = "MPL-2.0"
publish = false
readme = "README.md"
repository = "https://github.com/lmaotrigine/klip"
edition = "2024"

[dependencies]
blake2 = "0.11.0-rc.6"
chacha20 = { version = "0.10", features = ["xchacha"] }
clap = { version = "4", features = ["string", "wrap_help"] }
ctutils = "0.4"
ed25519-dalek = "3"
parking_lot = "0.12"
rand = { version = "0.10", features = ["std_rng"] }
scrypt = "0.12"
toml = { version = "1", default-features = false, features = ["parse", "serde"] }

[dependencies.tokio]
version = "1"
features = [
  "macros",
  "rt-multi-thread",
  "net",
  "io-util",
  "signal",
  "time",
]

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies]
tikv-jemallocator = "0.7"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61"
features = ["Win32_System_LibraryLoader"]

[lints.rust]
dead_code = "deny"
deprecated = "deny"
future_incompatible = "deny"
missing_copy_implementations = "deny"
missing_debug_implementations = "deny"
nonstandard_style = "deny"
rust_2018_idioms = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unused = "deny"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"

# our dependency tree is amenable to aggressive optimization without much
# compile time overhead. it still takes a bit, though.
[profile.release]
# on some platforms, opt-level = 3 performs better. i haven't profiled this
# extensively enough to make a decision.
opt-level = 2
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

[profile.deb]
inherits = "release"
debug = false

[package.metadata.deb]
section = "utils"
assets = [
  ["target/release/klip", "usr/bin/", "755"],
  ["LICENSE", "usr/share/doc/klip/", "644"],
  ["README.md", "usr/share/doc/klip/README", "644"],
  ["CHANGELOG.md", "usr/share/doc/klip/CHANGELOG", "644"],
  ["doc/klip.1", "usr/share/man/man1/klip.1", "644"],
  ["completions/klip.bash", "usr/share/bash-completion/completions/klip", "644"],
  ["completions/klip.fish", "usr/share/fish/vendor_completions.d/klip.fish", "644"],
  ["completions/_klip", "usr/share/zsh/vendor-completions/_klip", "644"],
  # elvish completions omitted on purpose
  # see https://github.com/elves/elvish/issues/1564
]
extended-description = """\
klip allows you to share arbitrary content between hosts anywhere on the
internet. It works by transferring the content to an intermediary server, which
every client with the correct credentials can query.
"""
depends = ""  # NOTE: will break unless target is x86_64-unknown-linux-musl
maintainer-scripts = "pkg/debian"

[package.metadata.deb.systemd-units]
unit-scripts = "pkg/systemd"
enable = false
start = false
