#!/bin/sh
set -eu

KLIP_CONF=/etc/klip.toml
KLIP_CONF_MODE=640
KLIP_HOME=/var/lib/klip/
KLIP_USER=klip

create_user() {
  if id $KLIP_USER >/dev/null 2>&1; then return; fi
  adduser --system --home $KLIP_HOME --group $KLIP_USER
}

generate_config() {
  klip genkeys | tail -n6
}

create_first_time_config() {
  if [ ! -f $KLIP_CONF ]; then
    generate_config > $KLIP_CONF
    chown $KLIP_USER:$KLIP_USER $KLIP_CONF
    chmod $KLIP_CONF_MODE $KLIP_CONF
  fi
}

case $1 in
  configure)
    create_user
    create_first_time_config
    ;;
esac

#DEBHELPER#
