index = "sparse+https://code.5ht2.me/api/packages/lmaotrigine/cargo/"

[target.'cfg(any(unix, windows))']
rustflags = [
  "-C", "target-cpu=native",
  "-C", "symbol-mangling-version=v0",
  #"-Z", "share-generics=y"
]

[target.'cfg(unix)']
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-Wl,--compress-debug-sections=zlib"
]

[target.'cfg(windows)']
rustflags = [
  "-C", "target-feature=+crt-static",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]

[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]

[target.armv7-unknown-linux-musleabihf]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]
